# Generated by Django 5.2 on 2025-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AddField(
            model_name='persona',
            name='id_persona',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
