# Generated by Django 5.2.1 on 2025-11-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_alter_adopcion_fecha_adopcion_and_more'),
        ('adopciones', '0004_persona_imagen'),
    ]

    operations = [
    ]
