# Generated by Django 5.2 on 2025-11-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0005_merge_20251103_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='id',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='id_adopcion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
